version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    image: ${DOCKER_USERNAME}/f5_evaluation_tool:latest
    environment:
      DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}"
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: